### PR TITLE
Trigger BREAKING CHANGE major release - Fixes #282

### LINKED ISSUE #282: Trigger BREAKING CHANGE from PR #278
The recent changes to Disk resource in #278 should trigger a major version number bump. Need to add a BREAKING CHANGE: commit

### PR DESCRIPTION
**Pull request by PlagueHO**
@johlju - this is a BREAKING CHANGE commit. I'm going to squash merge this into a new commit anyway (with BREAKING CHANGE) to trigger the major version bump.

#### Pull Request (PR) description

Administrative PR to force major version bump.,

#### This Pull Request (PR) fixes the following issues

- Fixes @282

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

@johlju - would you mind reviewing when you have time?

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/283)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/StorageDsc/283#-:-Nhx29Cx4-rvJzcUB0HK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Comment by johlju** [comment]
Not sure why the review message says it’s waiting for you @PlagueHO. All files looks good to me and can’t see I missed any. Very strange. 

Good to squash merge.

**Comment by johlju** [comment]
Btw the commit message “bump major version” suffice as commit message to. It looks for these keywords: 

https://github.com/dsccommunity/StorageDsc/blob/6473a60680135b3f577230af1da8316bca0f497c/GitVersion.yml#L3

**Comment by PlagueHO** [comment]
Thanks @johlju - hopefully will work now. I'll get you to remove the old preview package once the new 6 preview is published.

**Comment by johlju** [comment]
Since v6 was released I have unlisted the 5.2.0-preview1 version. It won’t show up in search results any longer.

**Pull request merged**
