### PR TITLE
Disk: Update Size value in example

### PR DESCRIPTION
**Pull request by fullenw1**
#### This Pull Request (PR) fixes the following issues
A value with a size unit (like MB or GB) does not work.
It generates the following error message:

> Compilation errors occurred while processing configuration 'DscConfigurationName'. Please review the errors reported in error stream and modify your configuration code appropriately.
> + CategoryInfo : InvalidOperation: (DscConfiguration:String) [], InvalidOperationException
> + FullyQualifiedErrorId : FailToProcessConfiguration

Entering only a number works fine.

#### Task list
- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/storagedsc/214)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @fullenw1 - that is really strange. Using 10GB etc should work and passes the example compilation tests. See: https://ci.appveyor.com/project/PowerShell/StorageDsc/branch/dev?fullLog=true#L565

How are you compiling the examples?

**Comment by fullenw1** [comment]
Hi @PlagueHO 
 
> How are you compiling the examples?

As I got the error message, I spotted by dichotomy the size parameter.
My intended value was different but I gave a try to 10GB like in the example (just copied/pasted the value) and got the same error.
When I used 10737418240 (the size in bytes), the error message disappeared.

By the way I got the exact same behavior on another resource:
https://github.com/PowerShell/ComputerManagementDsc/pull/278

**Comment by PlagueHO** [comment]
I tried this as well yesterday and you're right - it is failing. Not sure how the Example tests are passing though. That is something I should look into. Anyway, let's proceed with this change.

Can you add an entry into the CHANGELOG.MD for this change?

**Comment by fullenw1** [comment]
> Can you add an entry into the CHANGELOG.MD for this change?

Done!
Please have a look. First time I do this on a DSC module...

**Comment by PlagueHO** [comment]
Closing because superseded by #218

**Pull request closed without merging**
