### PR TITLE
MSFT_MountImage - Correcting example for dismounting an ISO image

### LINKED ISSUE #221: MSFT_MountImage - Dismounting an image fails Window Server 2019
https://github.com/dsccommunity/StorageDsc/blob/dev/Examples/Resources/MountImage/1-MountImage_DismountISO.ps1

Use the above example does not seem to work for me on Windows Server 2019 with an ISO mounted to drive Z:

```powershell
configuration MountImage_DismountISO
{
    Import-DscResource -ModuleName StorageDsc

    MountImage ISO
    {
        ImagePath = 'c:\software\SQLServer2019-x64-ENU-Dev.iso'
        DriveLetter = 'Z'
        Ensure = 'Absent'
    }
}
```

The error returned:

```
PowerShell DSC resource MSFT_MountImage  failed to execute Test-TargetResource functionality with error message:
System.InvalidOperationException: Ensure is 'Absent' but 'DriveLetter' was specified.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

### PR DESCRIPTION
**Pull request by wsmelton**
#### Pull Request (PR) description
The drive letter should not be provided when wanting to ensure an ISO is no longer mounted.

#### This Pull Request (PR) fixes the following issues

- Fixes #221 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/storagedsc/222)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Sorry about the delay @wsmelton - we've been a bit focused on the migration process over to the DSC Community. I've updated the build so that we can get this through.

**Comment by PlagueHO** [comment]
Hi @wsmelton - can you resolve the conflicts and correct the error: https://ci.appveyor.com/project/dsccommunity/storagedsc/builds/29743806?fullLog=true#L615

It just looks like the line length in the CHANGELOG.MD is beyond the 80 char limit.

**Comment by wsmelton** [comment]
So this would assume then that your test does not account for URL links being provided? If you ignore the URL link the whole line is only 71 characters.

**Comment by PlagueHO** [comment]
Hi @wsmelton - now that we've updated to the new pipeline/structure, are you still keen to complete this one?

**Pull request closed without merging**
